app:
  security:
    jwt-expiration-milliseconds: 864000000
    jwt-secret: mkfemwaklmfkewb432feawfwAFEWAFEFWA23441235fewafweFAWEFawfewfewafew523423432432
    authorized-redirect-uris:
      - http://localhost:3000/oauth2/redirect
    super-admins:
      - kasia@cwiakalska.com
      - tomasz.poniatowski@cytawa.com
      - szpak111@gmail.com
spring:
  datasource:
    username: ski
    url: jdbc:h2:mem:ski
    driverClassName: org.h2.Driver
    password: ski
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 910620874610-fd5e645l0lluug79i1a4ank14kjl9fij.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
server:
  port: '8080'
